templates:
  tv-series:
    configure_series:
      from:
        thetvdb_list:
          username: sgonzalezmo
          account_id: 3A1043265ADA0327
          strip_dates: yes
      settings:
        quality: 720p
        ep_regexp: Cap.(\d{1,2})(\d{2})
        set:
          content_filename: "{{ tvdb_series_name }} - {{ tvdb_ep_id }} - {{ tvdb_ep_name }}"
          main_file_only: yes
    series:
      - The Ministry of Time:
         alternate_name: El Ministerio Del Tiempo
    exists_series:
      path: /media/disk1/tvshows/{{ tvdb_series_name }}
      allow_different_qualities: better
    thetvdb_lookup: yes
    regexp:
      reject:
        - CENSORED: {from: title}
        - SCREENER: {from: title}
        - LATINO: {from: title}
        - VOS: {from: title}
        - V.O: {from: title}
        - SUBT: {from: title}
        - SUBS: {from: title}
        - INGLES: {from: title}
        - SUBTITUL: {from: title}
  torrent:
    private_torrents: no
    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: admin
      password: adminpwd123
tasks:
  download:
    priority: 1
    rss:
      url: http://feeds2.feedburner.com/newpctorrent
    template:
      - tv-series
      - torrent
  sort:
    priority: 2
    filesystem:
      path: /media/disk1/downloads/
      regexp: '.*\.(mkv)$'
      recursive: yes
      retrieve: files
    thetvdb_lookup: yes
    metainfo_series: yes
    require_field: [tvdb_series_name, tvdb_season, tvdb_ep_name, tvdb_ep_id]
    accept_all: yes
    seen: local
    disable:
      - seen
      - seen_info_hash
      - retry_failed
    move:
      to: /media/disk1/tvshows/{{ tvdb_series_name  }}/Season {{ tvdb_season|pad(2) }}
      rename: "{{ tvdb_series_name }} - {{ tvdb_ep_id }} - {{ tvdb_ep_name }}"
