templates:
  tv-series:
    configure_series:
      from:
        thetvdb_list:
          username: sgonzalezmo
          account_id: 3A1043265ADA0327
          strip_dates: yes
      settings:
        quality: 720p
        ep_regexp: Cap.(\d{1,2})(\d{2})
        set:
          content_filename: "{{ tvdb_series_name }} - {{ tvdb_ep_id }} - {{ tvdb_ep_name }}"
          main_file_only: yes
    exists_series:
      path: /media/disk1/tvshows/{{ tvdb_series_name }}
      allow_different_qualities: better
    thetvdb_lookup: yes
    private_torrents: no
    regexp:
      reject:
        - CENSORED: {from: title}
        - SCREENER: {from: title}
        - LATINO: {from: title}
        - VOS: {from: title}
        - V.O: {from: title}
        - SUBT: {from: title}
        - SUBS: {from: title}
        - INGLES: {from: title}
        - SUBTITUL: {from: title}
  torrent:
    transmission:
      enabled: yes
      host: localhost
      port: 9091
      username: admin
      password: 186sgosbdgrp
tasks:
  download:
    priority: 1
    rss:
      url: http://feeds2.feedburner.com/newpctorrent
    template:
      - tv-series
      - torrent
  sort:
    priority: 2
    filesystem:
      path: /media/disk1/downloads/
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    template: tv-series
    require_field:
      - series_name
      - series_season
    accept_all: yes
    move:
      to: /media/disk1/tvshows/{{ tvdb_series_name  }}/Season {{ tvdb_season|pad(2) }}
      rename: "{{ tvdb_series_name }}  - {{ tvdb_ep_id }} - {{ tvdb_ep_name }}"
